// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	core "github.com/leocov-dev/packwiz-nxt/core"
	mock "github.com/stretchr/testify/mock"
)

// MockUpdater is an autogenerated mock type for the Updater type
type MockUpdater struct {
	mock.Mock
}

type MockUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUpdater) EXPECT() *MockUpdater_Expecter {
	return &MockUpdater_Expecter{mock: &_m.Mock}
}

// CheckUpdate provides a mock function with given fields: _a0, _a1
func (_m *MockUpdater) CheckUpdate(_a0 []*core.Mod, _a1 core.Pack) ([]core.UpdateCheck, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CheckUpdate")
	}

	var r0 []core.UpdateCheck
	var r1 error
	if rf, ok := ret.Get(0).(func([]*core.Mod, core.Pack) ([]core.UpdateCheck, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func([]*core.Mod, core.Pack) []core.UpdateCheck); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.UpdateCheck)
		}
	}

	if rf, ok := ret.Get(1).(func([]*core.Mod, core.Pack) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdater_CheckUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckUpdate'
type MockUpdater_CheckUpdate_Call struct {
	*mock.Call
}

// CheckUpdate is a helper method to define mock.On call
//   - _a0 []*core.Mod
//   - _a1 core.Pack
func (_e *MockUpdater_Expecter) CheckUpdate(_a0 interface{}, _a1 interface{}) *MockUpdater_CheckUpdate_Call {
	return &MockUpdater_CheckUpdate_Call{Call: _e.mock.On("CheckUpdate", _a0, _a1)}
}

func (_c *MockUpdater_CheckUpdate_Call) Run(run func(_a0 []*core.Mod, _a1 core.Pack)) *MockUpdater_CheckUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]*core.Mod), args[1].(core.Pack))
	})
	return _c
}

func (_c *MockUpdater_CheckUpdate_Call) Return(_a0 []core.UpdateCheck, _a1 error) *MockUpdater_CheckUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdater_CheckUpdate_Call) RunAndReturn(run func([]*core.Mod, core.Pack) ([]core.UpdateCheck, error)) *MockUpdater_CheckUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// DoUpdate provides a mock function with given fields: _a0, _a1
func (_m *MockUpdater) DoUpdate(_a0 []*core.Mod, _a1 []any) error {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DoUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]*core.Mod, []any) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockUpdater_DoUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DoUpdate'
type MockUpdater_DoUpdate_Call struct {
	*mock.Call
}

// DoUpdate is a helper method to define mock.On call
//   - _a0 []*core.Mod
//   - _a1 []any
func (_e *MockUpdater_Expecter) DoUpdate(_a0 interface{}, _a1 interface{}) *MockUpdater_DoUpdate_Call {
	return &MockUpdater_DoUpdate_Call{Call: _e.mock.On("DoUpdate", _a0, _a1)}
}

func (_c *MockUpdater_DoUpdate_Call) Run(run func(_a0 []*core.Mod, _a1 []any)) *MockUpdater_DoUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]*core.Mod), args[1].([]any))
	})
	return _c
}

func (_c *MockUpdater_DoUpdate_Call) Return(_a0 error) *MockUpdater_DoUpdate_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUpdater_DoUpdate_Call) RunAndReturn(run func([]*core.Mod, []any) error) *MockUpdater_DoUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// GetName provides a mock function with no fields
func (_m *MockUpdater) GetName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockUpdater_GetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetName'
type MockUpdater_GetName_Call struct {
	*mock.Call
}

// GetName is a helper method to define mock.On call
func (_e *MockUpdater_Expecter) GetName() *MockUpdater_GetName_Call {
	return &MockUpdater_GetName_Call{Call: _e.mock.On("GetName")}
}

func (_c *MockUpdater_GetName_Call) Run(run func()) *MockUpdater_GetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUpdater_GetName_Call) Return(_a0 string) *MockUpdater_GetName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockUpdater_GetName_Call) RunAndReturn(run func() string) *MockUpdater_GetName_Call {
	_c.Call.Return(run)
	return _c
}

// ParseUpdate provides a mock function with given fields: _a0
func (_m *MockUpdater) ParseUpdate(_a0 map[string]any) (any, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for ParseUpdate")
	}

	var r0 any
	var r1 error
	if rf, ok := ret.Get(0).(func(map[string]any) (any, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(map[string]any) any); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}

	if rf, ok := ret.Get(1).(func(map[string]any) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockUpdater_ParseUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ParseUpdate'
type MockUpdater_ParseUpdate_Call struct {
	*mock.Call
}

// ParseUpdate is a helper method to define mock.On call
//   - _a0 map[string]any
func (_e *MockUpdater_Expecter) ParseUpdate(_a0 interface{}) *MockUpdater_ParseUpdate_Call {
	return &MockUpdater_ParseUpdate_Call{Call: _e.mock.On("ParseUpdate", _a0)}
}

func (_c *MockUpdater_ParseUpdate_Call) Run(run func(_a0 map[string]any)) *MockUpdater_ParseUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(map[string]any))
	})
	return _c
}

func (_c *MockUpdater_ParseUpdate_Call) Return(_a0 any, _a1 error) *MockUpdater_ParseUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockUpdater_ParseUpdate_Call) RunAndReturn(run func(map[string]any) (any, error)) *MockUpdater_ParseUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockUpdater creates a new instance of MockUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUpdater {
	mock := &MockUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
