// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	io "io"

	core "github.com/leocov-dev/packwiz-nxt/core"

	mock "github.com/stretchr/testify/mock"
)

// MockMetaDownloaderData is an autogenerated mock type for the MetaDownloaderData type
type MockMetaDownloaderData struct {
	mock.Mock
}

type MockMetaDownloaderData_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetaDownloaderData) EXPECT() *MockMetaDownloaderData_Expecter {
	return &MockMetaDownloaderData_Expecter{mock: &_m.Mock}
}

// DownloadFile provides a mock function with no fields
func (_m *MockMetaDownloaderData) DownloadFile() (io.ReadCloser, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for DownloadFile")
	}

	var r0 io.ReadCloser
	var r1 error
	if rf, ok := ret.Get(0).(func() (io.ReadCloser, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() io.ReadCloser); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(io.ReadCloser)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMetaDownloaderData_DownloadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadFile'
type MockMetaDownloaderData_DownloadFile_Call struct {
	*mock.Call
}

// DownloadFile is a helper method to define mock.On call
func (_e *MockMetaDownloaderData_Expecter) DownloadFile() *MockMetaDownloaderData_DownloadFile_Call {
	return &MockMetaDownloaderData_DownloadFile_Call{Call: _e.mock.On("DownloadFile")}
}

func (_c *MockMetaDownloaderData_DownloadFile_Call) Run(run func()) *MockMetaDownloaderData_DownloadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMetaDownloaderData_DownloadFile_Call) Return(_a0 io.ReadCloser, _a1 error) *MockMetaDownloaderData_DownloadFile_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMetaDownloaderData_DownloadFile_Call) RunAndReturn(run func() (io.ReadCloser, error)) *MockMetaDownloaderData_DownloadFile_Call {
	_c.Call.Return(run)
	return _c
}

// GetManualDownload provides a mock function with no fields
func (_m *MockMetaDownloaderData) GetManualDownload() (bool, core.ManualDownload) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetManualDownload")
	}

	var r0 bool
	var r1 core.ManualDownload
	if rf, ok := ret.Get(0).(func() (bool, core.ManualDownload)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func() core.ManualDownload); ok {
		r1 = rf()
	} else {
		r1 = ret.Get(1).(core.ManualDownload)
	}

	return r0, r1
}

// MockMetaDownloaderData_GetManualDownload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetManualDownload'
type MockMetaDownloaderData_GetManualDownload_Call struct {
	*mock.Call
}

// GetManualDownload is a helper method to define mock.On call
func (_e *MockMetaDownloaderData_Expecter) GetManualDownload() *MockMetaDownloaderData_GetManualDownload_Call {
	return &MockMetaDownloaderData_GetManualDownload_Call{Call: _e.mock.On("GetManualDownload")}
}

func (_c *MockMetaDownloaderData_GetManualDownload_Call) Run(run func()) *MockMetaDownloaderData_GetManualDownload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMetaDownloaderData_GetManualDownload_Call) Return(_a0 bool, _a1 core.ManualDownload) *MockMetaDownloaderData_GetManualDownload_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMetaDownloaderData_GetManualDownload_Call) RunAndReturn(run func() (bool, core.ManualDownload)) *MockMetaDownloaderData_GetManualDownload_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMetaDownloaderData creates a new instance of MockMetaDownloaderData. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetaDownloaderData(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetaDownloaderData {
	mock := &MockMetaDownloaderData{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
