// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	core "github.com/leocov-dev/packwiz-nxt/core"
	mock "github.com/stretchr/testify/mock"
)

// MockMetaDownloader is an autogenerated mock type for the MetaDownloader type
type MockMetaDownloader struct {
	mock.Mock
}

type MockMetaDownloader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetaDownloader) EXPECT() *MockMetaDownloader_Expecter {
	return &MockMetaDownloader_Expecter{mock: &_m.Mock}
}

// GetFilesMetadata provides a mock function with given fields: _a0
func (_m *MockMetaDownloader) GetFilesMetadata(_a0 []*core.Mod) ([]core.MetaDownloaderData, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for GetFilesMetadata")
	}

	var r0 []core.MetaDownloaderData
	var r1 error
	if rf, ok := ret.Get(0).(func([]*core.Mod) ([]core.MetaDownloaderData, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func([]*core.Mod) []core.MetaDownloaderData); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.MetaDownloaderData)
		}
	}

	if rf, ok := ret.Get(1).(func([]*core.Mod) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMetaDownloader_GetFilesMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFilesMetadata'
type MockMetaDownloader_GetFilesMetadata_Call struct {
	*mock.Call
}

// GetFilesMetadata is a helper method to define mock.On call
//   - _a0 []*core.Mod
func (_e *MockMetaDownloader_Expecter) GetFilesMetadata(_a0 interface{}) *MockMetaDownloader_GetFilesMetadata_Call {
	return &MockMetaDownloader_GetFilesMetadata_Call{Call: _e.mock.On("GetFilesMetadata", _a0)}
}

func (_c *MockMetaDownloader_GetFilesMetadata_Call) Run(run func(_a0 []*core.Mod)) *MockMetaDownloader_GetFilesMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]*core.Mod))
	})
	return _c
}

func (_c *MockMetaDownloader_GetFilesMetadata_Call) Return(_a0 []core.MetaDownloaderData, _a1 error) *MockMetaDownloader_GetFilesMetadata_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMetaDownloader_GetFilesMetadata_Call) RunAndReturn(run func([]*core.Mod) ([]core.MetaDownloaderData, error)) *MockMetaDownloader_GetFilesMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMetaDownloader creates a new instance of MockMetaDownloader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetaDownloader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetaDownloader {
	mock := &MockMetaDownloader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
